function Y = predict(X, ...
                     nn_weights, ...
                     input_layer_size, ...
                     hidden_layer_size, ...
                     output_layer_size)
  
  [a2, a3] = feedforward(X, ...
                         nn_weights, ...
                         input_layer_size, ...
                         hidden_layer_size, ...
                         output_layer_size);

  [~,Y] = max(a3,[],1);
  
end